### ISSUE TITLE
Proposed Fix for pre-commit flake8 EntryPoints object has no attribute get

### ISSUE THREAD

**Issue by teowenshen** [k2-fsa/icefall#652]
Hi, I've been facing this flake8 error for pre-commit, and this was the fix I found to be added in pre-commit-config.yaml. 

```yaml
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--max-line-length=80]
        additional_dependencies: ['importlib_metadata==4.3']
```
I was wondering - is anyone else facing this rather new issue? For me, it was the only way I can use the virtual environment by pre-commit. 
It does introduce a dependency to pre-commit though. If that is okay with you, I can send in a pull request to update this. 

Links:
https://github.com/python/importlib_metadata/issues/406#issuecomment-1264682770
https://github.com/python/importlib_metadata/issues/409#issuecomment-1265989849
